### ISSUE TITLE
Create Freelancer Description Page

### ISSUE THREAD

**Issue by ndricimrr** [ndricimrr/carcompanion-website#50]
**Description**
This is what is shown after you click on a freelancer.
shows all the data of the freelancer, and the buttns to book, inspect

**Possible Solution**
**Load data from a variable object and not static**
instead of:
<p> John </p

do: 

let freelancer ={ 
name: "John"
}

<p> {freelancer.name}</p

**Comment by HaifaHa** [comment]
![d4a16cc2-ffcb-4908-af19-c9ec3d6a8f04](https://user-images.githubusercontent.com/38734230/87048086-36461e00-c1f3-11ea-9f4e-eae7e2ba1112.jpeg)
